apiVersion: v1
kind: Service
metadata:
  labels:
    name: galera
  name: galera
spec:
  ports:
  # the port that this service should serve on
    - port: 3306
      targetPort: 3306
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: galera
#  publicIPs:
#    - 172.17.8.102
